### ISSUE TITLE
编译的一些问题

### ISSUE THREAD

**Issue by jiangfeng94** [DuelCode/ARToolkit#1]
在win32 环境下编译，ARvideo项目 videoQuickTime.c 文件 无法打开 "Movies.h" "MediaHandlers.h"等文件，在项目里也没找到这些头文件，请问这些头文件需要在哪里include？

**Comment by DuelCode** [comment]
sorry，长达一年多没有跟进这一技术了，编译环境和过程都快忘掉了。 印象中需要安装QuickTime SDK  for Windows 。 我学习使用时测试PC上的环境早已经被我卸载掉了。所以具体SDK的版本可能需要你自己进行尝试。建议安装最新版SDK，希望有帮助。
